### PR TITLE
support windows from facterdb

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mcanevet** [comment]
@mmoll I fixed unit tests on ruby 1.9 on master. Could you please rebase?
It will still fail because some windows facts are missing on old version of facter.

**Comment by mmoll** [comment]
what can be done about this? pin that test to the facter versions that have these facts?

**Comment by mcanevet** [comment]
@mmoll if it does not make sense to have facts for older versions of facter on windows than you can just skip the test on unsupported versions I guess

**Comment by mmoll** [comment]
:green_heart:

**Comment by mcanevet** [comment]
Thanks @mmoll

**Pull request merged**
