### PR TITLE
Add the env variable OS filter

### PR DESCRIPTION
**Pull request by dmitryilyin**
Fefactoring and cleanups
* Cleanup the methods and some minor
  refactoring without introducing any
  new featutres
* Add inline YARD documentation
  and yard doc actions to the Rakefile
* Refactoring and improvements of the
  RSpec tests

Add the OS filter support
If the SPEC_FACTS_OS variable is set only the matching OS'es
will be tested.

Example:
> SPEC_FACTS_OS='ubuntu-14' rake spec

It will test only on the Trusty Ubuntu even if there are more
supported OS'es in the metadata file.

### CODE REVIEW

**Comment by mcanevet** [comment]
@dmitryilyin could you please not mark unit tests as pending?

**Comment by dmitryilyin** [comment]
But almost all of them are marked as pending there.

**Comment by dmitryilyin** [comment]
ping

**Comment by mcanevet** [comment]
Test still pending...

**Comment by mcanevet** [comment]
@dmitryilyin o_O, there is way more things in this commit...
Some kind of automatic refactoring?

**Comment by dmitryilyin** [comment]
Nope, everything is done manually, it's just when you start fixing things you cannot stop)

**Comment by dmitryilyin** [comment]
Ah, and the PR comment was not auto-updated. Updated it manually.

**Comment by dmitryilyin** [comment]
Got 100% )

**Comment by mcanevet** [comment]
@dmitryilyin I really want to merge this, but it's quite big and unreadable right now... Would it be possible to split this in smaller commits?

**Comment by dmitryilyin** [comment]
And why do people always ask me this? I would always prefer to read a single large patch all in one place then a group of small patches. Besides, it's not easy to make them meaningful separately and they are nightmare to maintain and test.

Ok, i'll try to split this somehow...

**Comment by dmitryilyin** [comment]
I've managed to split only the refactoring and adding filter parts.

**Comment by mcanevet** [comment]
@dmitryilyin it's better but the first commit is still way too big IMHO.
Could you please split this 3 points in different commit?
* Cleanup the methods and some minor
  refactoring without introducing any
  new featutres
* Add inline YARD documentation
  and yard doc actions to the Rakefile
* Refactoring and improvements of the
  RSpec tests

I can do it myself if you don't have time. If so, do you want me to put you as the author of the commit?

**Comment by dmitryilyin** [comment]
Sigh... Ok, i've done as you requested

**Comment by mcanevet** [comment]
@dmitryilyin ok LGTM now. Thanks

**Pull request merged**
