### PR TITLE
Fix tests / symbolize strings

### PR DESCRIPTION
**Pull request by pjjw**
Apologies, decided to OCD fix up the unit tests that were marked FIXME after doing the last thing. This has both because I didn't want to write additional tests using string indexing.

### CODE REVIEW

**Comment by mcanevet** [comment]
@pjjw could you please rebase?

**Comment by mcanevet** [comment]
@pjjw cloud you please rebase?

**Comment by pjjw** [comment]
aggggh that's a nasty rebase :(

**Comment by pjjw** [comment]
this is unfortunately unlikely to happen :(

**Pull request closed without merging**
