### PR TITLE
Implement fact memoization

### LINKED ISSUE #114: Memoizing facts
Currently `on_supported_os` collects facts on every invocation. Typically it's called in every file with the same arguments (none). These calls can be slow and the result will be the same anyway. In https://github.com/voxpupuli/voxpupuli-test/commit/5fb4475db7ec25ce39bd9e4fbd667045a96b4006 I implemented memoization for voxpupuli-test.

Would this be a welcome addition to rspec-puppet-facts itself or should we keep it in voxpupuli-test?

### PR DESCRIPTION
**Pull request by ekohl**
Subsequent calls to on_supported_os with the same options should result in the same facts. This can greatly speed up testing by reducing calls to FacterDB.

This currently fails, probably because it's not taking environment variables into account. I did want to submit this since it's at least a start to collaborate.

Fixes #114

### CODE REVIEW

**Comment by ekohl** [comment]
I missed some cache keys, but I think I have them all now. Locally the tests were green so I think this is ready for review.

**Comment by ekohl** [comment]
The build failed on out of date components. Doesn't look related to my PR, just something that changed externally and probably also shows up in master.

**Comment by ekohl** [comment]
@mcanevet could you have a look?

**Comment by DavidS** [comment]
added the updated agent components

**Comment by mcanevet** [comment]
@DavidS is it OK for you to merge this?

**Comment by DavidS** [comment]
I'm running some local tests to confirm it working and being beneficial before merging.

I've also noticed that https://github.com/puppetlabs/puppet-module-gems/blob/9c488b456b3d3c1bc6fd02718ee95c102eb78211/config/dependencies.yml#L67 currently is excluding RPF v2 from being installed, so I'll fix that too.

**Comment by DavidS** [comment]
Results from my local tests:

```
# with released rspec-puppet-facts

Finished in 44 minutes 23 seconds (files took 3 minutes 20.2 seconds to load)
7803 examples, 0 failures


real	47m48.315s
user	46m6.912s
sys	1m16.671s
david@zion:~/git/puppetlabs-apache (main)$

# with modified rspec-puppet-facts
Finished in 42 minutes 47 seconds (files took 14.31 seconds to load)
7803 examples, 0 failures


real	43m5.625s
user	41m43.348s
sys	1m8.159s
david@zion:~/git/puppetlabs-apache (main)$
```

As you can see the file load time was reduced from 3 minutes 20 seconds down to 14 seconds. I consider that a great win (even when it doesn't make a big difference for this particular test suite).

**Comment by ekohl** [comment]
Thanks for merging this. Looking forward to a release that includes this.

> As you can see the file load time was reduced from 3 minutes 20 seconds down to 14 seconds. I consider that a great win (even when it doesn't make a big difference for this particular test suite).

It also helps greatly if you run something like `rspec -e mytest`. Note that the 14 seconds is dominated by a single `on_supported_os`. There's room for more improvement so I opened https://github.com/mcanevet/rspec-puppet-facts/issues/123 with some of my ideas.

**Pull request merged**
